import { Header } from '@/components';
import { HydrationBoundary, QueryClient, dehydrate } from '@tanstack/react-query';
import type { Metadata } from 'next';
import { ReactNode } from 'react';
import { ToastContainer } from 'react-toastify';
import { Providers } from './providers';
import 'react-toastify/dist/ReactToastify.css';

import '@/styles/reset.css';

export const metadata: Metadata = {
  title: '키보드 득템 :: KeyDuek',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const queryClient = new QueryClient();

  // 유저 data api 호출
  // const Token = cookies().get('accessToken')?.value ?? null;
  // await queryClient.prefetchQuery({ queryKey: ['userData'], queryFn: () => getUserData(Token), });

  return (
    <html lang='ko'>
      <body>
        <Providers>
          <HydrationBoundary state={dehydrate(queryClient)}>
            <ToastContainer
              position='top-center'
              style={{ width: 'max-content', padding: '2rem', fontSize: '1.6rem' }}
              autoClose={2000}
              closeButton={false}
              hideProgressBar
            />
            <Header />
            {children}
          </HydrationBoundary>
        </Providers>
      </body>
    </html>
  );
}
