#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="^(Feat|Fix|Bug|Docs|Style|Refactor|Chore|Test|Design|Build|Merge|Setting|Deploy):.*$"
if ! [[ $message =~ $requiredPattern ]];
then
  echo "=========================================================================="
  echo "======================   🚨 진심입니까 휴먼...?   ========================"
  echo "=========================================================================="
  echo "= Format should be => [header]: [What was done for Why]                 =="
  echo "= Allowed Headers: Feat, Fix, Docs, Style, Chore, Refactor, Design, Test ="
  echo "== EXAMPLE => Feat: Google login을 구현하였습니다                        =="
  echo "=========================================================================="
  echo "== Your commit message was =>" $message 
  echo "== For more information, check script in .husky/commit-msg or README.md =="
  echo "=========================================================================="
  exit 1
else
  echo "=========================================================================="
  echo "=======================        Quad8 화이팅!       ======================="
  echo "=========================================================================="
fi
